include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=NPing agent for OpenWrt
LUCI_DEPENDS:=+luci-base +curl

PKG_LICENSE:=Apache-2.0
PKG_VERSION:=1.0
PKG_MAINTAINER:=samlm0 <samlm0@pm.me>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
