name: Build

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          PACKAGES: luci-app-nping-agent
          NO_REFRESH_CHECK: true

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/action/*nping-agent*.ipk

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/packages/${{ matrix.arch }}/action/*nping-agent*.ipk
          file_glob: true
          tag: ${{ github.ref }}